# Generated by Django 4.2.2 on 2024-11-18 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Telefon raqami '+998901234567' formatida bo‘lishi kerak. Maksimal uzunlik 15 ta raqam.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
