# Generated by Django 4.2.2 on 2024-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0009_remove_user_phone_number_userinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='study_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='study_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
