# Generated by Django 4.2.2 on 2024-11-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0010_alter_userinfo_full_name_alter_userinfo_study_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='modelapp.user'),
        ),
    ]
