# Generated by Django 4.2.2 on 2024-11-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0012_alter_order_order_type_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip', to='modelapp.ordertype'),
        ),
    ]
