# Generated by Django 4.2.2 on 2024-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0016_message_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['user', 'id'], name='modelapp_me_user_id_3fa342_idx'),
        ),
    ]
