# Generated by Django 4.2.2 on 2024-12-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0017_message_modelapp_me_user_id_3fa342_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_id',
            new_name='file_url',
        ),
    ]
