# Generated by Django 4.2.2 on 2025-01-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0019_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_url',
            new_name='file_id',
        ),
    ]
